k9s:
  refreshRate: 2
  logBufferSize: 200
  logRequestSize: 200
  currentContext: minikube
  currentCluster: minikube
  dumpDir: /test
  clusters:
    minikube:
      namespace:
        active: kube-system
        favorites:
          - default
          - kube-public
          - istio-system
          - all
          - kube-system
      view:
        active: ctx
    fred:
      namespace:
        active: default
        favorites:
          - default
          - kube-public
          - istio-system
          - all
          - kube-system
      view:
        active: po
