project_name: k9s
before:
  hooks:
    - go mod download
    - go generate ./...

release:
  prerelease: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - -s -w -X github.com/derailed/k9s/internal/cmd.version={{.Version}} -X github.com/derailed/k9s/internal/cmd.commit={{.Commit}} -X github.com/derailed/k9s/internal/cmd.date={{.Date}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
brew:
  name: k9s
  github:
    owner: derailed
    name: k9s-homebrew-tap
  commit_author:
    name: derailed
    email: fernand@imhotep.io
  folder: Formula
  homepage: https://k9ss.io
  description: Kubernetes CLI To Manage Your Clusters In Style!
  test: |
    system "k9s version"
