project_name: k9s
before:
  hooks:
    - go mod download
    - go generate ./...
release:
  prerelease: false
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - armhf
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/derailed/k9s/cmd.version={{.Version}} -X github.com/derailed/k9s/cmd.commit={{.Commit}} -X github.com/derailed/k9s/cmd.date={{.Date}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      bit: Arm
      bitv6: Arm6
      bitv7: Arm7
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrews
brews:
  - name: k9s
    github:
      owner: derailed
      name: k9s-homebrew-tap
    commit_author:
      name: derailed
      email: fernand@imhotep.io
    folder: Formula
    homepage: https://k8sk9s.dev/
    description: Kubernetes CLI To Manage Your Clusters In Style!
    test: |
      system "k9s version"
