project_name: k9s
before:
  hooks:
    - go mod download
    - go generate ./...
release:
  prerelease: false
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/derailed/k9s/cmd.version=v{{.Version}} -X github.com/derailed/k9s/cmd.commit={{.Commit}} -X github.com/derailed/k9s/cmd.date={{.Date}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      bit: Arm
      bitv6: Arm6
      bitv7: Arm7
      # 386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
brews:
  - name: k9s
    tap:
      owner: derailed
      name: homebrew-k9s
    commit_author:
      name: derailed
      email: fernand@imhotep.io
    folder: Formula
    homepage: https://k9scli.io/
    description: Kubernetes CLI To Manage Your Clusters In Style!
    test: |
      system "k9s version"
