project_name: k9s
env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
    - go generate ./...

release:
  prerelease: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X github.com/derailed/k9s/cmd.version={{.Version}} -X github.com/derailed/k9s/cmd.commit={{.Commit}} -X github.com/derailed/k9s/cmd.date={{.Date}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    arm: 32-bit
    arm64: 64-bit
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
brew:
  name: k9s
  github:
    owner: derailed
    name: k9s-homebrew-tap
  commit_author:
    name: derailed
    email: fernand@imhotep.io
  folder: Formula
  homepage: https://k9ss.io
  description: Kubernetes CLI To Manage Your Clusters In Style!
  test: |
    system "k9s version"

# Snapcraft
snapcraft:
  name: k9s
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  publish: true
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
  summary: K9s is a CLI to view and manage your Kubernetes clusters.
  description: |
    K9s is a CLI to view and manage your Kubernetes clusters.
    By leveraging a terminal UI, you can easily traverse Kubernetes resources
    and view the state of you clusters in a single powerful session.
  grade: devel
  confinement: devel
  apps:
    k9s:
      plugs: ["home", "network"]

