repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$

      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        pass_filenames: false

      - id: go-build
        name: go build
        entry: go
        language: system
        args: [build, -v, ./...]
        pass_filenames: false
