name: Build k9s docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          eval `cat Dockerfile | grep 'K9S_VERSION' | head -1 | awk '{print $2}'`
          echo "K9S_VERSION=$K9S_VERSION" >> $GITHUB_ENV
      - name: Build and publish
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          image-name: ""
          image-tag: ${{ env.K9S_VERSION }}